### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by BalajiMalar** [alsa-project/tinycompress#12]
i was building yocto image which uses tinycomrpess as part of NXP's recipe-multimedia. the yocto build failed since it wasnt able to clone the package.
i tried to clone from CLI using the command "**git clone git://git.alsa-project.org/tinycompress.git**" and still it failed

**Comment by dbaluta** [comment]
You have two `git clone git clone` commands on the same line.

**Comment by BalajiMalar** [comment]
that was a typo

**Comment by perexg** [comment]
```
$ git clone git://git.alsa-project.org/tinycompress.git
Cloning into 'tinycompress'...
remote: Counting objects: 653, done.
remote: Compressing objects: 100% (380/380), done.
remote: Total 653 (delta 370), reused 460 (delta 267)
Receiving objects: 100% (653/653), 119.20 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (370/370), done.
```

```
$ git clone https://git.alsa-project.org/http/tinycompress.git
Cloning into 'tinycompress'...
Fetching objects: 653, done.
```

No problem here. Check your issues with your internet provider or local network administrator.

**Comment by SimonHYLu** [comment]
Dear All,

These days I try to build yacto with NXP image and got the same issue, and have tried the below command 

$git clone git://git.alsa-project.org/tinycompress.git

it shows 
fatal: repository 'https://git.alsa-project.org/tinycompress.git/' not found

Can anyone help? thank you!

**Comment by vinodkoul** [comment]
please use https://github.com/alsa-project/tinycompress insteadddd, i will update readme...

**Comment by perexg** [comment]
Vinod, keep also `git.alsa-project.org` in README - it's the official mirror on the ALSA server. No idea why it does not work - tried two machines in two different geographical locations - probably a firewall or so.

**Comment by SimonHYLu** [comment]
Gentlemen, it works now, thanks a lot!
