### ISSUE TITLE
What device should I have

### ISSUE THREAD

**Issue by Duty-rok** [alsa-project/tinycompress#21]
Hello, I am tesing your library now.
lsmod says that kernel has snd_compress module loaded.

I have file.mp3 and try to execute cplay next way:
    $ cplay file.mp3

Next logs were written to output:
    Unable to open Compress device 0:0
    ERR: cannot open device '/dev/snd/comprC0D0': No such file or directory

I looked through the contents of the /dev/snd/ folder and found nothing that had prefix 'compr'.

So, what device should I have to test it?

**Comment by plbossart** [comment]
Intel platforms use the compressed API for custom 'probe' support, that might be why you're seeing this.

Can you share the lsmod dependencies?

**Comment by Duty-rok** [comment]
Thank you for answer.
Lsmod output is attached in file:
[lsmod.txt](https://github.com/alsa-project/tinycompress/files/10187032/lsmod.txt)

**Comment by plbossart** [comment]
snd_compress           20480  2 snd_sof,snd_soc_core
snd_intel_sdw_acpi     16384  2 snd_sof_intel_hda_common,snd_intel_dspcfg

There you go. It's an Intel platform so there's no way to use this mp3 offload capability, not supported in firmware for this generation.

**Comment by Duty-rok** [comment]
Okey, thanks. Also what processors can I use for testing and how to understand, that they have mp3 offload capability?

**Comment by plbossart** [comment]
you need to ask @vinodkoul

**Comment by vinodkoul** [comment]
Hey, You can use https://www.96boards.org/product/rb3-platform/ this has mp3 offload enabled and ships with codec binaries. There are pulseaudio patches supporting offload by @ford-prefect as well
