### ISSUE TITLE
git clone failure

### ISSUE THREAD

**Issue by antonio-fr** [alsa-project/tinycompress#27]
Working on embedded project, there's a recipe for a system that uses tinycompress, and points to the alsa-project git server. Unfortunately, tinycompress can't be downloaded, leading the building system unable to make the system image.

```
$ git clone git://git.alsa-project.org/tinycompress.git
Cloning into 'tinycompress'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It worked yesterday, And I can see the project [there in the web interface](https://git.alsa-project.org/?p=tinycompress.git;a=tree). But right now, no luck.

**Comment by perexg** [comment]
It's fixed now.
