### ISSUE TITLE
Proposal for extending tinycompress to support plugins 

### ISSUE THREAD

**Issue by rohkkumar** [alsa-project/tinycompress#5]
Current tinycompress supports only interfacing directly with the ALSA kernel interface.
Proposal is to add support for tinycompress plugins for below reasons:
• Allow custom implementation of Compress modules in userspace
• Plugins can perform decoding/encoding.

To add this support, we have come up with the below design goals to make sure the impact is minimal
and the changes are helpful to the community of tinycompress users.
• Extend tinycompress functionality at run time/compile time to support plugins
• No change in any of the APIs exposed by tinycompress
• Re-use all existing tinycompress functionality for plugins
• Do not allow duplication of similar logic
• Plugins to adhere to same ALSA kernel interface (from asound.h/compress_params.h/compress_offload.h file)

The high level design to achieve this is as described below,
• Concept of virtual compress nodes similar to virtual PCM nodes and mixer nodes in tinyalsa.
• Virtual nodes defined in config file
• At compress_open call, first try to open kernel device node (present under /dev/snd/*).
• If Plugin support is enabled and kernel node open fails, try to open virtual node (defined in the config file).
• This information is retrieved by snd_utils which calls libsndcardparser.so and get information related to virtual node.
• Based on resolution at open assign function pointers for all functions at kernel interface level (ex: read/write/ioctl, etc).
• For kernel node, all function pointers implemented under new file compress_hw.c and all of them call into the kernel interface
• For virtual node, all function pointers implemented under new file compress_plugin.c, which interfaces with the plugin.
• Plugin itself is a .so library, dynamically dlopen’ed by the compress_plugin.c at open, and expected to register its ops to the framework (ex ops: open/read/write, etc)
• Plugin library name is stored in config file and is associated with card and device id.

The design is similar to plugin support in tinyalsa which was discussed in https://github.com/tinyalsa/tinyalsa/issues/135 and https://github.com/tinyalsa/tinyalsa/pull/137.

**Comment by vinodkoul** [comment]
Merged Pr#6
